### ISSUE TITLE
integrare autenticazione

### ISSUE THREAD

**Issue by gvaldambrini** [nbschool/ecommerce_web#15]
Sarà necessario integrare l'autenticazione, aggiungendo un pulsante (per ora mettiamolo da qualche parte in alto nella pagina) per fare il login. Una volta che il login è andato bene, sarà necessario fare le richieste impostando per ogni richiesta (ma cercando di non ripetere il codice mille volte):
```
    mode: 'cors',
    credentials: 'include',
```
In seguito al login sarà anche necessario salvare il fatto che è stato fatto il login su redux e/o su local storage. Possiamo andare verso la soluzione di usare un middleware per gestire la persistenza:
https://github.com/rt2zz/redux-persist
oppure andare a salvare la info su local storage prima che l'utente esca dalla pagina come mostrato qua:
https://stackoverflow.com/questions/36580963/can-you-or-should-you-use-localstorage-in-reduxs-initial-state

Chiaramente il valore è tenere aggiornato ogni volta che il server risponde 401 ad una richiesta.

**Comment by marcotinacci** [comment]
Link all'esempio di redirect su auth delle documentazione, fa praticamente come facevo io, non so se gli esempi sono aggiornati alla v4...
https://reacttraining.com/react-router/web/example/auth-workflow

**Comment by gvaldambrini** [comment]
certo che sono aggiornati, quello è l'esempio per la V4

**Comment by marcotinacci** [comment]
allora apposto
