### ISSUE TITLE
gestire l'internazionalizzazione

### ISSUE THREAD

**Issue by gvaldambrini** [nbschool/ecommerce_web#8]
Usiamo: https://github.com/yahoo/react-intl
Tutti i testi hardcodati nel codice dovranno essere convertiti in inglese, e andremo a fare la traduzione verso  l'italiano.

**Comment by toysroom** [comment]
Provo a spiegare quello che ho fatto.
Dunque, da quello che ho visto/capito io, https://github.com/yahoo/react-intl non è il package migliore per tradurre l'app e farla multilingua. In rete non c'è molto a riguardo, ma leggendo questo post https://www.facebook.com/groups/react.ita/permalink/1742379995998479/
sembra che react-intl ti dia tutte le utility di traduzione dei valori non in lingua ma in base alla lingua, quindi date, valute, plurali, ecc. Prob ci vorrà anche questo, ma per la traduzione brutale delle stringhe sembra sia da usare https://www.npmjs.com/package/i18next con il suo wrapper per react https://github.com/i18next/react-i18next
Perciò ho installato questi 2 packages

Per il momento io ho tradotto soltanto la stringa in ListItems che dice "Nessun item disponibile" / "no items available", giusto per vedere se come ho fatto è l’approccio giusto. Se ok, tradurrò anche le altre. Per switchare la lingua basta andare nel file src/i18n.js e cambiare la proprietà "lng" in "it" o "en"

in più i18next è molto amico di https://github.com/i18next/i18next-browser-languageDetector che recupera la lingua del browser e la imposta come predefinita salvandola in local storage. che faccio, lo metto? 

Se quello che ho fatto è ok, come faccio a simulare in storybook il cambiamento di lingua? faccio una storia in italiano ed una in inglese passandogli la lingua mockata come props? oppure?
